import Head from 'next/head';
import { default_font } from '@/src/lib/next-font';

export default function Home() {
    return (
        <>
            <Head>
                <title>KBN Task</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main style={default_font.style}>
                <h1 className="text-primary-500">Home Page</h1>
            </main>
        </>
    );
}
