import Head from 'next/head';
import { default_font } from '@/src/lib/next-font';
import HomeScreen from '@/src/screens/HomeScreen';

export default function Home() {
    return (
        <>
            <Head>
                <title>KBN Task</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`h-full ${default_font.className}`}>
                <HomeScreen />
            </main>
        </>
    );
}
